import type { APIRoute } from 'astro';
const SITE = 'https://stackarchitect.xyz';
const D = '2026-04-17';
const pages = [
  ['/', '1.0', 'weekly'],
  ['/tools', '0.9', 'weekly'],
  ['/shopify-automation-guides', '0.9', 'weekly'],
  ['/ultimate-shopify-automation-guide', '0.9', 'monthly'],
  ['/shopify-automation-scanner', '0.8', 'monthly'],
  ['/shopify-app-cost-calculator', '0.8', 'monthly'],
  ['/best-ai-tools-shopify', '0.8', 'monthly'],
  ['/pro', '0.9', 'monthly'],
  ['/privacy', '0.3', 'yearly'],
  ['/terms', '0.3', 'yearly'],
  ['/capi-shield', '0.9', 'monthly'],
  ['/stocky-swap', '0.9', 'monthly'],
  ['/tiktok-events-api-shopify', '0.9', 'monthly'],
  ['/replace-klaviyo-free', '0.8', 'monthly'],
  ['/shopify-profit-loss-automation', '0.8', 'monthly'],
  ['/autocrat-quota-fix', '0.8', 'monthly'],
  ['/analyzify-alternative', '0.7', 'monthly'],
  ['/elevar-alternative', '0.7', 'monthly'],
  ['/northbeam-alternative', '0.7', 'monthly'],
  ['/triple-whale-alternative', '0.7', 'monthly'],
  ['/stocky-alternative', '0.7', 'monthly'],
  ['/klaviyo-vs-systeme-io', '0.7', 'monthly'],
  ['/blog/google-apps-script-quotas-explained-how-to-avoid-limits-and-scale-your-automations', '0.8', 'monthly'],
  ['/blog/shopify-server-side-tracking-complete-setup-guide', '0.8', 'monthly'],
  ['/blog/shopify-agentic-storefronts-setup-guide-2026', '0.8', 'monthly'],
  ['/blog/shopify-meta-roas-dropped-2026-fix', '0.8', 'monthly'],
  ['/blog/zapier-vs-shopify-flow-vs-make', '0.7', 'monthly'],
  ['/blog/shopify-ai-playbook-2026', '0.7', 'monthly'],
  ['/blog/tidio-for-shopify-complete-setup-guide', '0.7', 'monthly'],
  ['/blog/make-com-shopify-automation-guide', '0.7', 'monthly'],
  ['/blog/klaviyo-vs-getresponse-shopify-2026', '0.7', 'monthly'],
  ['/blog/recover-lost-shopify-conversions-capi-shield', '0.7', 'monthly'],
  ['/blog/the-ultimate-guide-to-shopify-inventory-management', '0.7', 'monthly'],
  ['/blog/how-to-fix-shopify-conversion-tracking-after-ios-updates', '0.7', 'monthly'],
  ['/blog/the-lean-shopify-tech-stack-2026', '0.7', 'monthly'],
  ['/blog/how-much-shopify-apps-really-cost-and-how-to-cut-your-app-bill-in-half', '0.7', 'monthly'],
  ['/blog/shopify-apps-that-are-a-waste-of-money', '0.7', 'monthly'],
  ['/blog/tidio-vs-gorgias-shopify', '0.6', 'monthly'],
  ['/blog/when-to-upgrade-free-make-google-workspace', '0.6', 'monthly'],
  ['/blog/shopify-automation-stack-for-small-stores', '0.6', 'monthly'],
  ['/blog/the-complete-guide-to-reliable-shopify-automations', '0.6', 'monthly'],
  ['/blog/scalable-google-sheets-automation-for-high-volume-workflows', '0.6', 'monthly'],
  ['/blog/how-to-fix-service-invoked-too-many-times-in-google-apps-script', '0.6', 'monthly'],
  ['/blog/free-klaviyo-alternative-shopify-2026', '0.6', 'monthly'],
  ['/blog/replace-shopify-stocky-with-a-0-inventory-system', '0.7', 'monthly'],
  ['/blog/how-to-fix-shopify-google-ads-conversion-tracking-2026', '0.7', 'monthly'],
  ['/blog/shopify-stocky-data-export-before-shutdown', '0.7', 'monthly'],
  ['/blog/shopify-google-analytics-4-setup-free-2026', '0.7', 'monthly'],
];
export const GET: APIRoute = () => {
  const xml = `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${pages.map(([u,p,f])=>`  <url><loc>${SITE}${u}</loc><lastmod>${D}</lastmod><changefreq>${f}</changefreq><priority>${p}</priority></url>`).join('\n')}\n</urlset>`;
  return new Response(xml, { headers: { 'Content-Type': 'application/xml; charset=utf-8', 'Cache-Control': 'public, max-age=3600' } });
};
