/**
 * proofShots.ts — the registry of screenshot evidence on /pro/ and /pro/{slug}/.
 *
 * Brief §7: the page asks a stranger for card details, and a bullet list of
 * filenames is not evidence. These are the images that answer "does this
 * actually work". They are declared here, not inline in the templates, for the
 * same reason products.ts holds page copy: the four single pages render from
 * one template, so anything that forks on slug inside that template is how the
 * four pages drift apart.
 *
 * THE FILES ARE SUPPLIED BY HAND. They live in public/proof/ and are not
 * generated by anything. A missing file is not a build error — see
 * src/utils/proof.ts for why the frame renders in dev and is absent in prod.
 *
 * `captured` — the date a human took the screenshot, written into the caption.
 * Leave it undefined and the caption falls back to the file's own mtime, which
 * is correct for a screenshot saved straight into the repo and wrong for one
 * copied in later. Pin it explicitly rather than trusting the fallback: this
 * repo does not stamp dates nobody verified (CLAUDE.md, claims-guard).
 *
 * `width`/`height` are a fallback aspect only. The real dimensions are read out
 * of the PNG header at build time when the file exists, so the rendered
 * attributes always match the asset and the layout never shifts.
 */

export interface ProofShot {
  /** Basename inside public/proof/. */
  file: string;
  /** Descriptive alt — what a sighted buyer gains from the image. */
  alt: string;
  /** One line under the image saying what it shows. The date is appended. */
  caption: string;
  /** "27 Aug 2026". Undefined falls back to the file's mtime. */
  captured?: string;
  /** Fallback dimensions, used only while the file is absent. */
  width: number;
  height: number;
}

/** The /pro/ hero asset: all four scenarios in one Make.com canvas. */
export const KIT_HERO_SHOT: ProofShot = {
  file: 'scenario-all-in-one.png',
  alt: 'The Complete Kit scenario open in the Make.com canvas: one Shopify order webhook feeding a router that fans out to the Meta Conversions API, Google Ads Enhanced Conversions, the TikTok Events API and two Google Sheets modules.',
  caption:
    'All four automations running as one scenario in Make.com — one webhook, one router, five destinations.',
  width: 1600,
  height: 900,
};

/** The Make.com canvas for one blueprint. Keyed by product slug. */
export const SCENARIO_SHOTS: Record<string, ProofShot> = {
  'stocky-swap': {
    file: 'scenario-stocky-swap.png',
    alt: 'The Stocky Swap scenario in the Make.com canvas: a Shopify order webhook, an iterator over the order line items, and a Google Sheets Add a Row module.',
    caption: 'Blueprint 03 on the Make.com canvas, as it imports.',
    width: 1600,
    height: 900,
  },
  'capi-shield': {
    file: 'scenario-capi-shield.png',
    alt: 'The CAPI Shield scenario in the Make.com canvas: a Shopify order webhook feeding a SHA-256 hashing step, then a router splitting to the Meta Conversions API and Google Ads Enhanced Conversions.',
    caption: 'Blueprint 01 on the Make.com canvas, as it imports.',
    width: 1600,
    height: 900,
  },
  'tiktok-capi': {
    file: 'scenario-tiktok-capi.png',
    alt: 'The TikTok CAPI scenario in the Make.com canvas: a Shopify order webhook, an Advanced Matching field mapping, and an HTTP module posting CompletePayment to the TikTok Events API v1.3.',
    caption: 'Blueprint 02 on the Make.com canvas, as it imports.',
    width: 1600,
    height: 900,
  },
  'pnl-auto': {
    file: 'scenario-pnl-auto.png',
    alt: 'The P&L Auto scenario in the Make.com canvas: a Shopify order webhook, a COGS lookup against the template workbook, and a Google Sheets module writing revenue, fees, COGS and gross profit.',
    caption: 'Blueprint 04 on the Make.com canvas, as it imports.',
    width: 1600,
    height: 900,
  },
};

/**
 * The result the scenario produces — the half of the proof that shows the
 * events and rows actually arriving. Keyed by product slug; stocky-swap and
 * pnl-auto share one Sheets screenshot because they write to the same workbook.
 */
export const RESULT_SHOTS: Record<string, ProofShot> = {
  'capi-shield': {
    file: 'proof-meta-events.png',
    alt: 'Meta Events Manager showing a server-side Purchase event received from the Conversions API, with its event match quality score. Pixel and order identifiers are redacted.',
    caption:
      'The same order arriving in Meta Events Manager as a server event, with its match quality score. IDs redacted.',
    width: 1600,
    height: 900,
  },
  'tiktok-capi': {
    file: 'proof-tiktok-200.png',
    alt: 'TikTok Events Manager showing a CompletePayment test event received over the Events API v1.3, alongside the HTTP 200 returned to Make.com. Pixel code and access token are redacted.',
    caption:
      'A 200 back from the TikTok Events API, and the CompletePayment event in Events Manager. IDs redacted.',
    width: 1600,
    height: 900,
  },
  'stocky-swap': {
    file: 'proof-sheets-rows.png',
    alt: 'The Google Sheets inventory log populated with real order rows: timestamp, SKU, change amount, order ID, product and note. Order identifiers are redacted.',
    caption:
      'Real orders landing in the Sheets log — timestamp, SKU, quantity, order ID, product. Order IDs redacted.',
    width: 1600,
    height: 900,
  },
  'pnl-auto': {
    file: 'proof-sheets-rows.png',
    alt: 'The Google Sheets workbook populated with real order rows, with the Dashboard tab totalling revenue, fees, COGS and gross profit. Order identifiers are redacted.',
    caption:
      'Real orders landing in the workbook, with the Dashboard tab totalling itself. Order IDs redacted.',
    width: 1600,
    height: 900,
  },
};
