name: Google Indexing API
on:
  push:
    branches:
      - main

jobs:
  index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Google Indexing API
        uses: cuchi/jin-action@v1.1.0
        with:
          credentials: ${{ secrets.GOOGLE_INDEXING_KEY }}
          sitemap: "https://stackarchitect.xyz/sitemap-index.xml"
