name: Google Indexing API
on:
  push:
    branches:
      - main  # Make sure this matches your branch name (usually 'main')

jobs:
  index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Google Indexing API
        uses: goenning/google-indexing-action@v1
        with:
          credentials: ${{ secrets.GOOGLE_INDEXING_KEY }}
          sitemap: "https://stackarchitect.xyz/sitemap-index.xml"
